# Generated by Django 4.2.6 on 2023-10-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footwear',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1.99, max_digits=100),
        ),
        migrations.AlterField(
            model_name='lowerwear',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1.99, max_digits=100),
        ),
        migrations.AlterField(
            model_name='upperwear',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1.99, max_digits=100),
        ),
    ]
