# Generated by Django 4.2.6 on 2023-10-31 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_alter_footwear_price_alter_lowerwear_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footwear',
            name='quatity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='footwear',
            name='size',
            field=models.CharField(choices=[('XXL', 'Very extra Large'), ('XL', 'Extra Large'), ('L', 'Large'), ('M', 'Medium'), ('S', 'Small')], default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lowerwear',
            name='quatity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lowerwear',
            name='size',
            field=models.CharField(choices=[('XXL', 'Very extra Large'), ('XL', 'Extra Large'), ('L', 'Large'), ('M', 'Medium'), ('S', 'Small')], default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upperwear',
            name='quatity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='upperwear',
            name='size',
            field=models.CharField(choices=[('XXL', 'Very extra Large'), ('XL', 'Extra Large'), ('L', 'Large'), ('M', 'Medium'), ('S', 'Small')], default=1, max_length=5),
            preserve_default=False,
        ),
    ]
