# Generated by Django 4.2.6 on 2023-12-25 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_footwear_quatity_footwear_size_lowerwear_quatity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footwear',
            name='size',
        ),
        migrations.RemoveField(
            model_name='lowerwear',
            name='size',
        ),
        migrations.RemoveField(
            model_name='upperwear',
            name='size',
        ),
    ]
