# Generated by Django 4.2.6 on 2023-12-27 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_someothermodel_delete_bookinstance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SomeOtherModel',
        ),
    ]
