# Generated by Django 4.2.6 on 2023-10-23 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Posti', '0002_ordermodel_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='customer',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='PName',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='PPrice',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Posti.customer'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
