# Generated by Django 4.2.6 on 2023-10-23 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posti', '0004_remove_ordermodel_date_customer_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date',
            field=models.DateTimeField(verbose_name='date-published'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='PPrice',
            field=models.DecimalField(decimal_places=2, default=1.99, max_digits=100),
        ),
    ]
