# Generated by Django 4.2.6 on 2023-10-29 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posti', '0006_alter_customer_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
