# Generated by Django 4.2.6 on 2023-10-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posti', '0007_alter_customer_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='PPrice',
            field=models.DecimalField(decimal_places=2, default=1.99, max_digits=1000),
        ),
    ]
