# Generated by Django 4.2.6 on 2023-10-31 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posti', '0009_alter_customer_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='Quatity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='Size',
            field=models.CharField(choices=[('XXL', 'Very extra Large'), ('XL', 'Extra Large'), ('L', 'Large'), ('M', 'Medium'), ('S', 'Small')], default=1, max_length=5),
            preserve_default=False,
        ),
    ]
