# Generated by Django 4.2.6 on 2023-11-01 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posti', '0011_rename_quatity_ordermodel_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='Quantity',
            field=models.IntegerField(),
        ),
    ]
