# Generated by Django 4.2.6 on 2023-12-22 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posti', '0012_alter_ordermodel_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='user',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
