# Generated by Django 4.2.6 on 2023-12-25 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posti', '0015_remove_customer_date_ordermodel_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.FileField(upload_to='image')),
                ('PName', models.CharField(max_length=50)),
                ('PPrice', models.DecimalField(decimal_places=2, default=1.99, max_digits=1000)),
                ('Quantity', models.IntegerField()),
            ],
        ),
    ]
