# Generated by Django 4.2.6 on 2023-12-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posti', '0016_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('U', 'Upper'), ('L', 'Lower'), ('F', 'Foot')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
