# Generated by Django 4.2.6 on 2024-03-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posti', '0017_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='oredered',
            field=models.BooleanField(default=False),
        ),
    ]
